### ISSUE TITLE
Move to ES6

### ISSUE THREAD

**Issue by ai** [logux/logux-server#18]
1. Add `node4` to Logux ESLint config with [`no-unsupported-features` and `no-deprecated-api`](https://github.com/mysticatea/eslint-plugin-node) and force to use ES6 features.
2. Update JS code.

**Comment by lamartire** [comment]
#19 My solution. I not remove repo with config. When you make the choice, I will change this dependency.

**Comment by frsv** [comment]
This PR has some differences with merged config, but I really love your solution with template literals! Unfortunately, I've missed that.  I guess it would be better you to update your PR instead of creating another one with my changes.

@ai, what do you think?

**Comment by frsv** [comment]
@ai maybe should you close this issue?

**Comment by ai** [comment]
Sure, forgot about it
