### ISSUE TITLE
Use Jest snapshots

### ISSUE THREAD

**Issue by okonet** [logux/logux-server#2]
I was wondering why did you write your own snapshots mechanism instead of just using Jest's built in?

**Comment by ai** [comment]
I thought that Jets snapshots was for React, but when I find real case of snapshots own snapshots syste, was already done :).

**Comment by ai** [comment]
We could migrate to Jest snapshots. Main problem — how preview snapshots output? Like I use `./test/snapshots/update` to debug repoprters.

**Comment by okonet** [comment]
That's the best part of Jest snapshots: they are just strings.

In order to preview them we could create a script similar to you have already (read all `__snapshots__` dir and output it the `process.stdout` minus the Jest's version wrapper. Not sure Jest has support for printing snapshots at the moment, but this might be a good PR to the lib itself I think.

**Comment by ai** [comment]
Sure. I have a TODO about it. I will migrate to them when I will have free time.

Also PR is welcome. If you will migrate a tests, I could write a display tool :).

**Comment by okonet** [comment]
Awesome, I'll take a look when I have some free time as well! Let's close the issue when it's done.

**Comment by okonet** [comment]
I think I'll tackle the read tool in one PR as well so no worries here.

**Comment by ai** [comment]
OK. @PavloKovalov moved all tests to Jest snapshots, but I need also snapshot output tool (something like `./test/__snapshots__/print`).
