### ISSUE TITLE
Allow to provide a reporter to the Server

### ISSUE THREAD

**Issue by ertrzyiks** [logux/logux-server#41]
Hi,

I'm trying to add tests for my server class and to do that I need to pass a reporter mock. It's possible only with `BaseServer`, but `Server` class builds reporter on it's own.

```js
class MyServer extends Server {
 ...
}

new MyServer(options, reporterMock) // it doesn't work
```

The solution could be to inherit from `BaseServer` and copy-paste the bootstrap code from `Server`

```js
class MyServer extends BaseServer {
 ...copy paste Server code here
}

new MyServer(options, reporterMock) // it works!
```

What do you think about adding an option to override reporter in Server class as well? Or maybe compose Server with BaseServer instead of inherit from it?

**Comment by ai** [comment]
I like the idea too override reporter in Server, good idea.

Please send PR.
