### ISSUE TITLE
handle action order/dependency

### ISSUE THREAD

**Issue by salzhrani** [logux/logux-server#48]
### Goal
Allow the business logic to identify dependencies between actions if any and apply them in any order.

### Problem
When there is a reliable connection to the server the actions are applied in order they are received. But when the connection is intermittent, the client send a batch of actions and the server handles them in reverse order (newest action first), which has great benefits but doesn't count for the business logic having any preference.
For example:
on the client the following actions are created

1. C1: create user
2. C2: update user.name to "john"

in case of a good connection, the server handles C1 then C2, resulting in a valid user object.

in case of a bad connection the server receives a batch of [C2, C1] and handles C2, then C1 which might result in invalid user object.

### Expectation
Either the server allows the for specifying the order to process actions, or it supplies the batch of actions to the handler and shift the responsibility to the business logic to figure out.

**Comment by ai** [comment]
Fixed https://github.com/logux/logux-sync/commit/c914c556ac2db7de588cadbac6e118fb4296f9f1

**Comment by ai** [comment]
I will need a day to fix Jest 22 problems and release fix

**Comment by ai** [comment]
Released in Logux Sync 0.2.3.
