### ISSUE TITLE
reporter enhancement request

### ISSUE THREAD

**Issue by nevf** [logux/logux-server#51]
I am using ```reporter.logger``` in my server code which accepts ```( action, meta, msg )``` params. I'd like to include other Objects in the Bunyan log. 

Could an optional object param be added after ```msg``` for this purpose. Or is there some other way I can do this. 

Right now I am merging my object with ```meta```, which is not ideal.

**Comment by ai** [comment]
What exactly you want to change? :)

Or show your server and logger code.

**Comment by nevf** [comment]
As per my previous post I've written this simple function:
````
/** Display spec'd info using the Logux specified logger to the console.
 */
function debug_logger( action, meta, msg ){
    app.reporter.logger.info( { action: action, meta: jsome.getColoredString( meta ) }, msg || '' )
}
````
I'd like to be able to include other objects in the Bunyan log so something like:
````
function debug_logger( action, meta, msg, other_obj ){
    app.reporter.logger.info(  { action: action, meta: meta }, msg || '',  other_obj || {} )
or
    app.reporter.logger.info(  { action: action, meta: meta, other_obj: other_obj || {}  }, msg || '')
}
````
I hope that helps explain things.

**Comment by ai** [comment]
Where and how do you use this `debug_logger`?

**Comment by nevf** [comment]
I call it in my server code which uses logux server. For example in ```app.channel( ..)``` I call

````
debug_logger( action, Object.assign( {}, meta, { params: params, creator: creator } ), 'app.channel()' )
````
so I can include params and creator in the Bunyan log. However it would be much better I could do something like:
````
debug_logger( action, meta, 'app.channel()', { params: params, creator: creator } )
````
or something like that.

**Comment by ai** [comment]
In `debug_logger` you don't need any special support from Logux. Just write directly to Bunyan instance in `server.reporter`
