### ISSUE TITLE
app.auth callback should return promise 

### ISSUE THREAD

**Issue by Mavrin** [logux/logux-server#9]
I don't know maybe it is bug or to need add notice in documentation
if I make
```
app.auth(token => {
 return true;
})
```
I get error.

**Comment by ai** [comment]
You are right. Please send PR (docs are best to get PRs for free :D).

**Comment by ai** [comment]
Also you deserve to get into Logux Server history at least for first part of args/env PR. Sad that I could not select 2 person as PR authors :).
